// Generated by https://quicktype.io

export interface PlacesResponse {
    type:        string;
    query:       string[];
    features:    Feature[];
    attribution: string;
}

export interface Feature {
    id:            string;
    type:          string;
    place_type:    string[];
    relevance:     number;
    properties:    Properties;
    text_es:       string;
    language_es:   Language;
    place_name_es: string;
    text:          string;
    language:      Language;
    place_name:    string;
    bbox:          number[];
    center:        number[];
    geometry:      Geometry;
    context:       Context[];
}

export interface Context {
    id:          ID;
    short_code:  Language;
    wikidata:    Wikidata;
    text_es:     Text;
    language_es: Language;
    text:        Text;
    language:    Language;
}

export enum ID {
    Country8774 = "country.8774",
    Region17478 = "region.17478",
    Region230470 = "region.230470",
}

export enum Language {
    Es = "es",
    EsM = "ES-M",
    EsSa = "ES-SA",
}

export enum Text {
    España = "España",
    ProvinciaDeMadrid = "provincia de Madrid",
    ProvinciaDeSalamanca = "provincia de Salamanca",
}

export enum Wikidata {
    Q24004405 = "Q24004405",
    Q29 = "Q29",
    Q71080 = "Q71080",
}

export interface Geometry {
    type:        string;
    coordinates: number[];
}

export interface Properties {
    wikidata: string;
}
